"""create transcript_verifications

Revision ID: 15be2ed0dffa
Revises: 
Create Date: 2026-03-27 17:39:02.357694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15be2ed0dffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.String(length=255), nullable=False),
    sa.Column('applicant_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_staff_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_transcript_verifications_applicant_id'), 'transcript_verifications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_transcript_verifications_assigned_staff_id'), 'transcript_verifications', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_transcript_verifications_status'), 'transcript_verifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_verifications_status'), table_name='transcript_verifications')
    op.drop_index(op.f('ix_transcript_verifications_assigned_staff_id'), table_name='transcript_verifications')
    op.drop_index(op.f('ix_transcript_verifications_applicant_id'), table_name='transcript_verifications')
    op.drop_table('transcript_verifications')
    # ### end Alembic commands ###
