"""add flag_reviews table

Revision ID: 2b168f4b7153
Revises: 15be2ed0dffa
Create Date: 2026-03-27 17:53:59.656551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b168f4b7153'
down_revision: Union[str, None] = '15be2ed0dffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flag_reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('flag_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('staff_user_id', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['transcript_verifications.verification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_flag_reviews_flag_id'), 'flag_reviews', ['flag_id'], unique=False)
    op.create_index(op.f('ix_flag_reviews_staff_user_id'), 'flag_reviews', ['staff_user_id'], unique=False)
    op.create_index(op.f('ix_flag_reviews_verification_id'), 'flag_reviews', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flag_reviews_verification_id'), table_name='flag_reviews')
    op.drop_index(op.f('ix_flag_reviews_staff_user_id'), table_name='flag_reviews')
    op.drop_index(op.f('ix_flag_reviews_flag_id'), table_name='flag_reviews')
    op.drop_table('flag_reviews')
    # ### end Alembic commands ###
